<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Database1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[Order]" Member="Order">
    <Type Name="Order">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="products" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="quantity" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="User_Order" Member="User" ThisKey="user_id" OtherKey="id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Processor" Member="Processor">
    <Type Name="Processor">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="hash" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="price" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="User">
    <Type Name="User">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="passwd" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="adress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="role" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="User_Order" Member="Order" ThisKey="id" OtherKey="user_id" Type="Order" />
    </Type>
  </Table>
</Database>